/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  obsUtilsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome'
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'doc',
      id: 'migrate-from-v4',
      label: 'Migrate from v4',
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'overlay-editor',
        'triggers',
        'overlay-animations',
        'bundles',
        'stream-overlay-css',
        'obs-remote',
        'multi-gm',
        'scene-presets',
        'camera-keyframes',
        'manual-mode',
        'api',
        'director-api'
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-reference'
        }
      ]
    }
  ],
};

module.exports = sidebars;
